### ISSUE TITLE
IE11 compatibility

### ISSUE THREAD

**Issue by guillaumewuip** [krisk/Fuse#374]
It seems the IE11 compatibility is broken with `5.0.10-beta` .

I use webpack to bundle my app and, looking at your rollup config, I think it's probably because webpack use the lib `package.json` `module` field when possible.

https://github.com/krisk/Fuse/blob/aa636e62ac2572c879d1fdf4e1d3e50cfc450da7/package.json#L9

If I understand correctly your rollup config, it outputs ES6 (both ES6 modules and other ES6 features) for the esm bundle.
https://github.com/krisk/Fuse/blob/aa636e62ac2572c879d1fdf4e1d3e50cfc450da7/scripts/configs.js#L61-L66

Should not the esm bundle be ES5 with ES6 module import/export for tree shaking like explained for example [here](https://github.com/webpack/webpack/issues/1979#issuecomment-339738809)?

Something like this for the `tsconfig.json`

```json
{
  "compilerOptions": {
    "module": "es6",
    "target": "es5",
...
```

Let me know if I can help with a PR :)

**Comment by krisk** [comment]
Want to create a PR for this?

**Comment by guillaumewuip** [comment]
Yes 👍

**Comment by guillaumewuip** [comment]
Looking further on the IE11 crash error, we see this 
![image (1)](https://user-images.githubusercontent.com/748586/78336112-1cab8f80-758f-11ea-841c-557c697c68c6.png)

This seems to be the babel result of this line https://github.com/krisk/Fuse/blob/e5d4c1c152f6d1cb761b2dc62060e32181f04003/src/search/bitap-search/bitap-score.js#L3

To be IE11 compatible, we should not have object spreading here. It's looks like babel is not removing those.

**Comment by guillaumewuip** [comment]
#381 should fix this

**Comment by evanmoses-okta** [comment]
This should still be open until #383 is merged.

**Comment by slorber** [comment]
agree, this is still a problem to me and not sure which version > 5.x I can use with a fix for IE11 / Edge 18.

Afaik the only solution is to ask webpack's babel loader to transpile this lib
